"""Create or reset the controlled data set used by the Locust scenarios.

Idempotent: re-running resets inventory to the requested quantities, so every
run starts from the same, known stock. Everything goes through the public API,
so it works against any environment the API can reach (never point it at
production data).

    python seed.py --host http://localhost:8080

Creates (if missing):
  * user      loadtest@example.com (password from LOCUST_PASSWORD, or a
              generated one stored in loadtest.env)
  * category  "Load Test"
  * products  LOADTEST-0001..N with --stock units each (order/mixed traffic)
  * product   LOADTEST-CONTENTION with --contention-stock units (contention)

and writes locust/loadtest.env, which every scenario loads automatically.
Inventory is reset with reserved_quantity=0; orders left open by earlier runs
keep their rows but no longer hold reserved stock.
"""
import argparse
import os
import secrets
import sys
from pathlib import Path

import requests

ENV_FILE = Path(__file__).resolve().parent / "loadtest.env"
CATEGORY = "Load Test"
CONTENTION_SKU = "LOADTEST-CONTENTION"


def read_env_file():
    values = {}
    if ENV_FILE.is_file():
        for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
            if "=" in line and not line.lstrip().startswith("#"):
                key, value = line.split("=", 1)
                values[key.strip()] = value.strip()
    return values


def data(response):
    response.raise_for_status()
    return response.json().get("data")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--host", default=os.getenv("LOCUST_HOST", "http://localhost:8080"))
    parser.add_argument("--email", default=os.getenv("LOCUST_EMAIL", "loadtest@example.com"))
    parser.add_argument("--products", type=int, default=10, help="number of general load-test products")
    parser.add_argument("--stock", type=int, default=1_000_000, help="available units per general product")
    parser.add_argument("--contention-stock", type=int, default=100, help="available units for the contention product")
    args = parser.parse_args()

    host = args.host.rstrip("/")
    saved = read_env_file()
    password = os.getenv("LOCUST_PASSWORD") or saved.get("LOCUST_PASSWORD") or secrets.token_urlsafe(18)
    api = requests.Session()

    created = api.post(f"{host}/api/v1/users", json={
        "first_name": "Load", "last_name": "Test", "email": args.email, "password": password,
    }, timeout=10)
    if created.status_code not in (200, 201, 409):
        sys.exit(f"creating user failed: HTTP {created.status_code} {created.text}")

    login = api.post(f"{host}/api/v1/auth/login", json={"email": args.email, "password": password}, timeout=10)
    if login.status_code != 200:
        sys.exit(f"login as {args.email} failed (HTTP {login.status_code}); "
                 "the user exists with another password: set LOCUST_PASSWORD")
    api.headers["Authorization"] = f"Bearer {login.json()['data']['token']}"

    category = next((c for c in data(api.get(f"{host}/api/v1/categories", timeout=30)) or [] if c["name"] == CATEGORY), None)
    if category is None:
        category = data(api.post(f"{host}/api/v1/categories", json={
            "name": CATEGORY, "description": "Fixtures for Locust load tests"}, timeout=10))

    existing = {p["sku"]: p for p in data(api.get(f"{host}/api/v1/products", timeout=30)) or []}

    def ensure_product(sku, name, price):
        product = existing.get(sku)
        if product is None:
            product = data(api.post(f"{host}/api/v1/products", json={
                "name": name, "description": "Locust load-test fixture", "sku": sku,
                "price": price, "category_id": category["id"]}, timeout=10))
        return product["id"]

    def reset_inventory(product_id, quantity):
        response = api.get(f"{host}/api/v1/inventory/{product_id}", timeout=10)
        if response.status_code == 404:
            data(api.post(f"{host}/api/v1/inventory", json={
                "product_id": product_id, "available_quantity": quantity}, timeout=10))
        else:
            response.raise_for_status()
            data(api.put(f"{host}/api/v1/inventory/{product_id}", json={
                "available_quantity": quantity, "reserved_quantity": 0}, timeout=10))

    product_ids = []
    for index in range(1, args.products + 1):
        product_id = ensure_product(f"LOADTEST-{index:04d}", f"Load Test Product {index}", 10 + index)
        reset_inventory(product_id, args.stock)
        product_ids.append(product_id)

    contention_id = ensure_product(CONTENTION_SKU, "Load Test Contention Product", 5)
    reset_inventory(contention_id, args.contention_stock)

    ENV_FILE.write_text("\n".join([
        "# Generated by seed.py. Local load-test fixture credentials; do not commit.",
        f"LOCUST_EMAIL={args.email}",
        f"LOCUST_PASSWORD={password}",
        f"LOCUST_PRODUCT_IDS={','.join(product_ids)}",
        f"LOCUST_CONTENTION_PRODUCT_ID={contention_id}",
        "",
    ]), encoding="utf-8")

    print(f"user {args.email}; {len(product_ids)} products x {args.stock} units; "
          f"contention product {contention_id} x {args.contention_stock} units")
    print(f"wrote {ENV_FILE}")


if __name__ == "__main__":
    main()
